version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cibuilds/hugo:0.53
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: apk add git-subtree
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: git config --global user.name "itkq"
      - run: git config --global user.email "re@itkq.jp"
      - run: ./script/deploy.sh
