name: Publish site

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish site with hugo

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.53'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
